MyBlog/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('course/', include('course.urls')),
    path('docs/', include('doc.urls')),
    path('', include('verifications.urls')),
    path('admin/', include('admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 将media文件加入到url中

apps/course/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/30 16:01
# @Author  : wjh
# @File    : urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_list, name='index'),
    path('<int:course_id>/', views.CourseDetailViews.as_view(), name='course_detail'),
]

apps/course/models.py
from django.db import models

from utils.models import ModelBase


class Teacher(ModelBase):
    name = models.CharField(max_length=150, verbose_name='讲师姓名', help_text='讲师姓名')
    positional_title = models.CharField(max_length=150, verbose_name='职称', help_text='职称')
    profile = models.TextField(verbose_name='简介', help_text='简介')
    avatar_url = models.URLField(default='', verbose_name='头像url', help_text='头像url')

    class Meta:
        db_table = 'tb_teachers'
        verbose_name = '讲师'
        verbose_name_plural = verbose_name


class CourseCategory(ModelBase):
    name = models.CharField(max_length=100, verbose_name='课程分类名')

    class Meta:
        db_table = 'tb_course_category'
        verbose_name = '课程分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Course(ModelBase):
    title = models.CharField(max_length=150, verbose_name='课程名', help_text='课程名')
    cover_url = models.URLField(verbose_name='课程封面图URL', help_text='课程封面图URL')
    video_url = models.URLField(verbose_name='课程视频URL', help_text='课程视频URL')
    duration = models.FloatField(default=0.0, verbose_name='课程时长', help_text='课程时长')
    profile = models.TextField(null=True, blank=True, verbose_name="课程简介", help_text='课程简介')
    outline = models.TextField(null=True, blank=True, verbose_name="课程大纲", help_text='课程大纲')

    teacher = models.ForeignKey('Teacher', on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey('CourseCategory', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        db_table = 'tb_course'
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

apps/course/views.py
import logging

from django.shortcuts import render
from django.views import View
from django.http import Http404

from . import models

logger = logging.getLogger('django')


def course_list(request):
    course = models.Course.objects.only('title', 'cover_url', 'teacher__positional_title').filter(is_delete=False)
    return render(request, 'course/course(1).html', locals())


class CourseDetailViews(View):
    '''handle course_detail'''

    def get(self, request, course_id):
        '''get请求，返回课程详情页面'''
        try:
            course = models.Course.objects.only('title', 'cover_url', 'video_url', 'profile', 'outline', 'teacher__name', 'teacher__avatar_url', 'teacher__positional_title', 'teacher__profile').select_related('teacher').filter(is_delete=False, id=course_id).first()
            return render(request, 'course/course_detail.html', locals())
        except models.Course.DoesNotExist as e:
            logger.info('当前课程出现如下异常：\n{}'.format(e))
            raise Http404('<h1>此课程不存在！</h1>')

templates/course/course(1).html
{% extends 'base/base.html' %}

{% block title %}
  课程页
{% endblock %}

{% block link %}
  <link rel="stylesheet" href={% static 'css/course/course.css' %}>
{% endblock %}

{% block main_start %}
  <main id="course-container">
    <div class="w1200">
      <ul class="course-list">
        {% for foo in course %}
          <li class="course-item">
            <a href={% url 'course:course_detail' foo.id %}>
              <img class="course-img" src={{ foo.cover_url }}
                 alt={{ foo.title }}>
              <div class="course-content">
                <p class="course-info">{{ foo.title }}</p>
                <p class="course-author">{{ foo.teacher.name }}</p>
                <p class="course-price free">免费</p>
              </div>
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </main>
{% endblock %}

templates/course/course_detail.html
{% extends 'base/base.html' %}

{% block title %}
  课程详情页
{% endblock %}

{% block link %}
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta name="author" content="handsomeFu"/>
  <link rel="stylesheet" href={% static 'css/course/course-detail.css' %}>
{% endblock %}

{% block main_start %}
<!-- main-contain start  -->
  <main id="main">
    <div class="w1200">
      <div class="course-contain">
        <div class="course-top-contain">
          <h4 class="course-title">{{ course.title }}</h4>
          <div class="course-other clearfix">
            <div class="share-list">
              <span>分享至:</span>
              <i class="PyWhich py-weibo"></i>
            </div>
            <div class="buy-list">
              <span class="price">免费</span>
            </div>
          </div>
        </div>

        <div class="course-video" id="course-video">
          <span class="course-data" style="display: none;" data-video-url="{{ course.video_url }}"
                data-cover-url="{{ course.cover_url }}">
          </span>
        </div>

        <div class="course-bottom-contain">
          <div class="course-detail-list">
            <div class="course-item clearfix">
              <h5 class="course-title">{{ course.teacher.name }}</h5>
              <div class="teacher-box clearfix">
                <img src="{{ course.teacher.avatar_url }}" alt="{{ course.teacher.name }}"
                     title="{{ course.teacher.name }}" class="teacher-avatar">
                <div class="teacher-info">
                  <p class="teacher-name">{{ course.teacher.name }}</p>
                  <p class="teacher-identify">{{ course.teacher.positional_title }}</p>
                </div>
              </div>
              <div class="item-content">
                {{ course.teacher.profile }}
              </div>
            </div>
            <div class="course-item clearfix">
              <h5 class="course-title">课程简介</h5>
              <div class="item-content">
                {{ course.profile }}
              </div>
            </div>
            <div class="course-item clearfix">
              <h5 class="course-title">课程大纲</h5>
              <div class="item-content">
                <p>{{ course.outline }}</p>
              </div>
            </div>
            <div class="course-item clearfix">
              <h5 class="course-title">帮助中心</h5>
              <div class="item-content">
                <p>1. 购买后的课程在线可反复观看学习，视频有效期以具体课程信息为准。 </p>
                <p>2. 课程暂不支持下载观看，均为在线观看视频。 </p>
                <p>3. 课程一经购买，不可转让、不可退款；仅限购买账号观看。</p>
                <p>4. 如有问题请咨询客服: 400-1567-315 </p>
              </div>
            </div>
            <div class="course-item clearfix">
              <h5 class="course-title">关于学习计划</h5>
              <div class="item-content">
                关于学习的计划问题，pywjh还是希望大家能够按照自己的学习进度，合理的安排学习计划，作到劳逸结合，
                这样不至于学的很累。还能保持新鲜感，如果每天都干着同一件事情，总是会烦的，是吧。就这样吧，我们都要加油哦，
                好好找一份心仪的工作，照顾好自己，照顾好家人，照顾好老婆和孩子。
              </div>
            </div>
          </div>
          <div class="course-side">
            <h4 class="side-title">推荐课程</h4>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}
<!-- main-contain  end -->


{% block script %}
  <script src="https://cdn.bdstatic.com/jwplayer/latest/cyberplayer.js"></script>
  <script src="{% static 'js/course/course_detail.js' %}"></script>
{% endblock %}