MyBlog/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('course/', include('course.urls')),
    path('docs/', include('doc.urls')),
    path('', include('verifications.urls')),
    path('admin/', include('admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 将media文件加入到url中

apps/news/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/27 22:26
# @Author  : wjh
# @File    : urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/banners/', views.NewsBannerView.as_view(), name='news_banners'),
    path('news/<int:news_id>/', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/<int:news_id>/comments/', views.NewsCommentView.as_view(), name='news_comment'),
    path('news_detail/', views.NewsDetailView.as_view(), name='news_detail'),
    path('search/', views.SearchView(), name='search'),
]


apps/news/models.py
import pytz
from django.db import models

from utils.models import ModelBase
from django.conf import settings


class Tag(ModelBase):
    '''
    create tag models
    '''
    name = models.CharField(max_length=64, verbose_name='标签名', help_text='标签名')

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = 'tb_tag' # 指明数据库表明
        verbose_name = '新闻标签' # 在admin站点中显示的名称
        verbose_name_plural = verbose_name # 显示的复数形式的名称

    def __str__(self):
        return self.name

class News(ModelBase):
    '''
    create news models
    '''
    title = models.CharField(max_length=150, verbose_name="标题", help_text="标题")
    digest = models.CharField(max_length=200, verbose_name="摘要", help_text="摘要")
    content = models.TextField(verbose_name="内容", help_text="内容")
    clicks = models.IntegerField(default=0, verbose_name="点击量", help_text="点击量")
    image_url = models.URLField(default="", verbose_name="图片url", help_text="图片url")
    tag = models.ForeignKey('Tag', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = 'tb_news' # 指明数据库表明
        verbose_name = '新闻'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Comment(ModelBase):
    '''
    create comment models
    '''
    content = models.TextField(verbose_name='内容', help_text='内容')
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)
    news = models.ForeignKey('News', on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='son_comments')

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = 'tb_comments'
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def to_dict_data(self):
        # shanghai_tz = pytz.timezone(settings.TIME_ZONE)
        # update_time_local = shanghai_tz.normalize(self.update_time)
        comment_dict = {
            'news_id': self.news.id,
            'content_id': self.id,
            'content': self.content,
            'author': self.author.username,
            # 'update_time': update_time_local.strftime('%Y年%m月%d日 %H:%M'),
            'update_time': self.update_time.strftime('%Y年%m月%d日 %H:%M'),
            'parent': self.parent.to_dict_data() if self.parent else None,
        }

        return comment_dict

    def __str__(self):
        return '<评论{}>'.format(self.id)


class HotNews(ModelBase):
    '''
    create HotNews model 热闻
    '''
    PRI_CHOICES = [
        (1, '第一级'),
        (2, '第二级'),
        (3, '第三级'),
    ]
    news = models.OneToOneField('News', on_delete=models.CASCADE)
    priority = models.IntegerField(verbose_name='优先级', help_text='优先级')

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = 'tb_hotnews' # 指明数据库表明
        verbose_name = '热门新闻' # 在admin站点中显示的名称
        verbose_name_plural = verbose_name

    def __str__(self):
        return '<热门新闻{}>'.format(self.id)


class Banner(ModelBase):
    '''
    create banner models 轮播图
    '''
    PRI_CHOICES = {
        (1, '第一级'),
        (2, '第二级'),
        (3, '第三级'),
        (4, '第四级'),
        (5, '第五级'),
        (6, '第六级'),
    }
    image_url = models.URLField(verbose_name='轮播图url', help_text='轮播图url')
    priority = models.IntegerField(choices=PRI_CHOICES, default=5,verbose_name='优先级', help_text='优先级')
    news = models.OneToOneField('News', on_delete=models.CASCADE)

    class Meta:
        ordering=['priority', '-update_time', '-id']
        db_table = 'tb_banner'
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '<轮播图{}>'.format(self.id)

apps/news/views.py
import json
import logging

from django.shortcuts import render
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseNotFound
from haystack.views import SearchView as _SearchView
from django.conf import settings

from . import models
from . import contants
from utils.json_fun import to_json_data
from utils.res_code import Code, error_map


logger = logging.getLogger('django')


class IndexView(View):
    '''
    handle index
    route: no url path
    '''

    def get(self, request):
        '''get请求，返回首页'''
        tags = models.Tag.objects.only('id', 'name').filter(is_delete=False)
        hot_news = models.HotNews.objects.select_related('news').only('news__title', 'news__image_url', 'news_id').filter(is_delete=False).order_by('priority', '-news__clicks')[:contants.SHOW_HOT_NEWS_COUNT]
        return render(request, 'news/index.html', locals())


# 1. 创建一个类视图
# 2. 获取前端传过来的参数
# 3. 校验参数
# 4. 从数据库中获取news数据
# 5. 分页展示内容
# 6. 返回json格式的数据
class NewsListView(View):
    '''
    create news list view
    route: /news/
    // 127.0.0.1:8000/news?tag_id=1&page=1
    '''
    def get(self, request):
        try:
            # 获取前端点击返回的tag， 错误请求直接返回0（最新资讯）
            tag_id = int(request.GET.get('tag_id', 0))
        except Exception as e:
            logger.error("标签错误: \n{}".format(e))
            tag_id = 0

        try:
            # 获取前端返回的页数请求，错误请求直接返回第一页
            page = int(request.GET.get('page', 1))
        except Exception as e:
            logger.error('当前页错误: \n{}'.format(e))
            page = 1

        # 关联查询数据，only过滤数据
        news_queryset = models.News.objects.select_related('tag', 'author').\
            only('title', 'digest', 'image_url', 'update_time', 'tag__name', 'author__username')
        # 从数据库中取出数据，操作有误就直接返回全部数据
        news = news_queryset.filter(is_delete=False, tag_id=tag_id) or news_queryset.filter(is_delete=False)

        paginator = Paginator(news, contants.PER_PAGE_NEWS_COUNT)
        try:
            news_info = paginator.page(page)
        except PageNotAnInteger:
            logging.info("用户请求非整形页")
            news_info = paginator.page(1)
        except EmptyPage:
            # 若用户访问的页数大于实际页数，则返回最后一页数据
            logging.info("用户访问的页数大于总页数。")
            news_info = paginator.page(paginator.num_pages)

        # 序列化输出
        news_info_list = []
        for i in news_info:
            news_info_list.append({
                'id': i.id,
                'title': i.title,
                'digest': i.digest,
                'image_url': i.image_url,
                'tag_name': i.tag.name,
                'author': i.author.username,
                'update_time': i.update_time.strftime('%Y年%m月%d日 %H:%M'),
            })
        # 创建返回前端的数据
        data = {
            'total_pages': paginator.num_pages,
            'news': news_info_list
        }

        return to_json_data(data=data)


class NewsBannerView(View):
    '''
    news banner view
    route: news/banners/
    '''
    def get(self, request):
        banners = models.Banner.objects.select_related('news').only('image_url', 'news_id', 'news__title').filter(is_delete=False)[:contants.SHOW_BANNER_COUNT]

        banners_info_list = []
        for b in banners:
            banners_info_list.append({
                'image_url': b.image_url,
                'news_id': b.news.id,
                'news_title': b.news.title
            })
        data = {
            'banners': banners_info_list
        }
        return to_json_data(data=data)


class NewsDetailView(View):
    '''handle news_detail'''

    def get(self, request, news_id):
        '''get请求，返回详情页'''
        news = models.News.objects.select_related('tag', 'author').only('title', 'content', 'update_time', 'tag__name', 'author__username').filter(is_delete=False, id=news_id).first()
        if news:
            comments = models.Comment.objects.select_related('author', 'parent').only('content', 'author__username', 'update_time','parent__author__username', 'parent__content', 'parent__update_time').filter(is_delete=False, news_id=news_id)
            # 序列化输出
            comments_list = []
            for comm in comments:
                comments_list.append(comm.to_dict_data())

            comment_num = len(comments_list)

            return render(request, 'news/news_detail.html', locals())
        else:
            return HttpResponseNotFound('<h1>Page not found!</h1>')


class NewsCommentView(View):
    '''
    create news's comments
    route: /news/<int:news_id>/comment/
    '''
    def post(self, request, news_id):
        if not request.user.is_authenticated: # 如果用户没有登陆，不允许添加自评论
            return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.SESSIONERR])

        if not models.News.objects.only('id').filter(is_delete=False, id=news_id).exists():
            return to_json_data(errno=Code.PARAMERR, errmsg='文章不存在')

        # 从前端获取参数
        json_data = request.body
        if not json_data:
            return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.UNKOWNERR])
        dict_data = json.loads(json_data.decode('utf-8'))

        content = dict_data.get('content')
        # 获取用户评论
        if not content:
            return to_json_data(errno=Code.PARAMERR, errmsg='评论不能为空')
        parent_id = dict_data.get('parent_id')
        try:
            if parent_id:
                parent_id = int(parent_id)
                if not models.Comment.objects.only('id'). \
                    filter(is_delete=False, id=parent_id,
                           news_id=news_id).exists():
                    return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])

        except Exception as e:
            logging.info("前端传过来的parent_id异常：\n{}".format(e))
            return to_json_data(errno=Code.PARAMERR, errmsg="未知异常")

            # 保存到数据库
        new_content = models.Comment()
        new_content.content = content
        new_content.news_id = news_id
        new_content.author = request.user
        new_content.parent_id = parent_id if parent_id else None
        new_content.save()

        return to_json_data(data=new_content.to_dict_data())


class SearchView(_SearchView):
    # 模版文件
    template = 'news/search.html'

    # 重写响应方式，如果请求参数q为空，返回模型News的热门新闻数据，否则根据参数q搜索相关数据
    def create_response(self):
        kw = self.request.GET.get('q', '')
        if not kw:
            show_all = True
            hot_news = models.HotNews.objects.select_related('news'). \
                only('news__title', 'news__image_url', 'news__id'). \
                filter(is_delete=False).order_by('priority', '-news__clicks')

            paginator = Paginator(hot_news, settings.HAYSTACK_SEARCH_RESULTS_PER_PAGE)
            try:
                page = paginator.page(int(self.request.GET.get('page', 1)))
            except PageNotAnInteger:
                # 如果参数page的数据类型不是整型，则返回第一页数据
                page = paginator.page(1)
            except EmptyPage:
                # 用户访问的页数大于实际页数，则返回最后一页的数据
                page = paginator.page(paginator.num_pages)
            return render(self.request, self.template, locals())
        else:
            show_all = False
            qs = super(SearchView, self).create_response()
            return qs

templates/news/index.html
{% extends 'base/base.html' %}
{% block title %}
  首页
{% endblock %}

<!-- css link start -->
{% block link %}
  <link rel="stylesheet" href={% static 'css/news/index.css' %}>
{% endblock %}
<!-- css link end -->

<!-- main-contain start  -->
{% block main_contain %}
  <div class="main-contain">
    <!-- banner start -->
    <div class="banner">
      <ul class="pic">
{#        <!--淡入淡出banner-->#}
{##}
{##}
{#        <li><a href="javascript:void(0);"><img src={% static 'images/linux.jpg' %} alt="test"></a></li>#}
{##}
{##}
{#        <li><a href="javascript:void(0);"><img src={% static 'images/python_gui.jpg' %} alt="test"></a></li>#}
{##}
{##}
{#        <li><a href="javascript:void(0);"><img src={% static 'images/python_function.jpg' %} alt="test"></a></li>#}
{##}
{##}
{#        <li><a href="javascript:void(0);"><img src={% static 'images/python_advanced.jpg' %} alt="test"></a></li>#}
{##}
{##}
{#        <li><a href="javascript:void(0);"><img src={% static 'images/jichujiaochen.jpeg' %} alt="test"></a></li>#}
{##}
{##}
{#        <li><a href="javascript:void(0);"><img src={% static 'images/python_web.jpg' %} alt="test"></a></li>#}


      </ul>
      <a href="javascript:void(0);" class="btn prev">
        <i class="PyWhich py-arrow-left"></i></a>
      <a href="javascript:void(0);" class="btn next">
        <i class="PyWhich py-arrow-right"></i></a>
      <ul class="tab">
        <!-- 按钮数量必须和图片一致 -->


{#        <li></li>#}
{##}
{##}
{#        <li></li>#}
{##}
{##}
{#        <li></li>#}
{##}
{##}
{#        <li></li>#}
{##}
{##}
{#        <li></li>#}
{##}
{##}
{#        <li></li>#}


      </ul>
    </div>
    <!-- banner end -->

    <!-- content start -->
    <div class="content">
      <!-- recommend-news start -->
      <ul class="recommend-news">
        {% for hot_new in hot_news %}
           <li>
          <a href={% url 'news:news_detail' hot_new.news_id %} target="_blank">
            <div class="recommend-thumbnail">
              <img src="{{ hot_new.news.image_url }}" alt="{{ hot_new.news.title }}">
            </div>
            <p class="info">{{ hot_new.news.title }}</p>
          </a>
        </li>
        {% endfor %}

      </ul>
      <!-- recommend-news end -->

      <!--  news-nav start-->
      <nav class="news-nav">
        <ul class="clearfix">
          <li class="active"><a href="javascript:void(0)">最新资讯</a></li>

          {% for tag in tags %}
            <li><a href="javascript:void(0)" data-id="{{ tag.id }}">{{ tag.name }}</a></li>
          {% endfor %}


          {#          <li><a href="javascript:void(0)" data-id="1">python框架</a>#}
          {#          </li>#}
          {##}
          {#          <li><a href="javascript:void(0)" data-id="2">Python基础</a>#}
          {#          </li>#}
          {##}
          {#          <li><a href="javascript:void(0)" data-id="3">Python高级</a>#}
          {#          </li>#}
          {##}
          {#          <li><a href="javascript:void(0)" data-id="4">Python函数</a>#}
          {#          </li>#}
          {##}
          {#          <li><a href="javascript:void(0)" data-id="5">PythonGUI</a>#}
          {#          </li>#}
          {##}
          {#          <li><a href="javascript:void(0)" data-id="6">Linux教程</a>#}
          {#          </li>#}

        </ul>
      </nav>
      <!--  news-nav end -->

      <!-- news-contain start -->
      <div class="news-contain">
        <ul class="news-list">

        </ul>
      </div>
      <!-- news-contain end -->

      <!-- btn-more start -->
      <a href="javascript:void(0);" class="btn-more">加载更多</a>
      <!-- btn-more end -->
    </div>
    <!-- content end -->
  </div>
{% endblock %}
<!-- main-contain  end -->

{% block side %}
  <!-- side start -->
  <aside class="side">
    <div class="side-activities">
      <h3 class="activities-title">在线课堂<a href="javascript:void(0)">更多</a></h3>
      <div class="activities-img">
        <a href="javascript:void(0);" target="_blank">
          <img src={% static 'images/english.jpg' %} alt="title">
        </a>
        <p class="activities-tips">对话国外小姐姐</p>
      </div>
      <ul class="activities-list">
        <li>
          <a href="javascript:void(0);" target="_blank">
            <span class="active-status active-start">报名中</span>
            <span class="active-title"><a
               href="https://www.shiguangkey.com/course/2432"> Django 项目班</a></span>
          </a>
        </li>
        <li>
          <a href="javascript:void(0);" target="_blank">
            <span class="active-status active-end">已结束</span>
            <span class="active-title"><a
               href="https://www.shiguangkey.com/course/2321">Python入门基础班</a></span>
          </a>
        </li>
      </ul>
    </div>
    <div class="side-attention clearfix">
      <h3 class="attention-title">关注我</h3>
      <ul class="side-attention-address">
        <li>
          <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-GitHub"></i>pywjh</a>
        </li>
        <li>
          <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-zhihu"
                                                           style="color:rgb(0, 108, 226);"></i>pywjh</a>
        </li>
        <li>
          <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-weibo"
                                                           style="color:rgb(245,92,110);"></i>pywjh</a>
        </li>
      </ul>
      <div class="side-attention-qr">
        <p>扫码关注</p>
      </div>
    </div>

    {% block hot_recommend %}
      <div class="side-hot-recommend">
        <h3 class="hot-recommend">热门推荐</h3>
        <ul class="hot-news-list">

          <li>
            <a href="javascript:void(0)" class="hot-news-contain clearfix">
              <div class="hot-news-thumbnail">
                <img src={% static 'images/python_web.jpg' %}
                        alt="">
              </div>
              <div class="hot-news-content">
                <p class="hot-news-title">Django调试工具django-debug-toolbar安装使用教程</p>
                <div class="hot-news-other clearfix">
                  <span class="news-type">python框架</span>
                  <!-- 自带的 -->
                  <time class="news-pub-time">11月11日</time>
                  <span class="news-author">python</span>
                </div>
              </div>
            </a>
          </li>

        </ul>
      </div>
    {% endblock %}

  </aside>
  <!-- side end -->
{% endblock %}

{% block script %}
  <script src={% static 'js/news/index.js' %}></script>
{% endblock %}

templates/news/news_detail.html
{% extends 'base/base.html' %}

<!-- css title start -->
{% block title %}
  文章详情页
{% endblock %}
<!-- css title end -->

{% block link %}
  <link rel="stylesheet" href="{% static 'css/news/news-detail.css' %}">
{% endblock %}

<!-- main-contain start  -->
{% block main_contain %}
  <div class="main-contain">
    <!-- news-contain start  -->
    <div class="news-contain">
      <h1 class="news-title">{{ news.title }}</h1>
      <div class="news-info">
        <div class="news-info-left">
          <span class="news-author">{{ news.author.username }}</span>
          <span class="news-pub-time">{{ news.uptate_time }}</span>
          <span class="news-type">{{ news.tag.name }}</span>
        </div>
      </div>
      <article class="news-content">
        {{ news.content|safe }}
      </article>
      <div class="comment-contain">
        <div class="comment-pub clearfix">
          <div class="new-comment">
            文章评论(<span class="comment-count">{{ comment_num }}</span>)
          </div>

          {% if user.is_authenticated %}
            <div class="comment-control logged-comment" news-id="{{ news.id }}">
              <input type="text" placeholder="请填写评论">
              <button class="comment-btn">发表评论</button>
            </div>
          {% else %}
            <div class="comment-control please-login-comment" news-id="{{ news.id }}">
              <input type="text" placeholder="请登录后参加评论" readonly>
              <button class="comment-btn">发表评论</button>
            </div>
          {% endif %}

        </div>

        <ul class="comment-list">
          {% for one_comment in comments_list %}
            <li class="comment-item">
              <div class="comment-info clearfix">
                <img src="{% static 'images/avatar.jpeg' %}" alt="avatar" class="comment-avatar">
                <span class="comment-user">{{ one_comment.author }}</span>
              </div>
              <div class="comment-content">{{ one_comment.content }}</div>

              {% if one_comment.parent %}
                <div class="parent_comment_text">
                  <div class="parent_username">{{ one_comment.parent.author }}</div>
                  <br/>
                  <div class="parent_content_text">
                    {{ one_comment.parent.content }}
                  </div>
                </div>
              {% endif %}

              <div class="comment_time left_float">{{ one_comment.update_time }}</div>
              <a href="javascript:;" class="reply_a_tag right_float">回复</a>
              <form class="reply_form left_float" comment-id="{{ one_comment.content_id }}"
                    news-id="{{ one_comment.news_id }}">
                <textarea class="reply_input"></textarea>
                <input type="button" value="回复" class="reply_btn right_float">
                <input type="reset" name="" value="取消" class="reply_cancel right_float">
              </form>

            </li>
          {% endfor %}

        </ul>
      </div>

    </div>
  </div>
  <!-- news-contain end  -->
{% endblock %}
<!-- main-contain  end -->

{% block script %}
  <script src="{% static 'js/news/news-detail.js' %}"></script>

{% endblock %}