MyBlog/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('course/', include('course.urls')),
    path('docs/', include('doc.urls')),
    path('', include('verifications.urls')),
    path('admin/', include('admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 将media文件加入到url中

apps/doc/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/30 16:47
# @Author  : wjh
# @File    : urls.py
from django.urls import path

from . import views

app_name = 'doc'

urlpatterns = [
    path('doc_download/', views.doc_index, name='index'),
    path('<int:doc_id>/', views.DocDownload.as_view(), name='doc_download'),
]

apps/doc/models.py
from django.db import models

from utils.models import ModelBase


class Doc(ModelBase):
    '''
    create doc model
    '''
    file_url = models.URLField(verbose_name='文件url', help_text='文件url')
    title = models.CharField(max_length=150, verbose_name='文档标题', help_text='文档标题')
    desc = models.TextField(verbose_name='文档描述', help_text='文档描述')
    image_url = models.URLField(default='', verbose_name='图片url', help_text='图片url')
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)

    class Meta:
        db_table = 'tb_docs' # 指明数据库名
        verbose_name = '文档' # 在admin站点中显示的名称
        verbose_name_plural = verbose_name

    def  __str__(self):
        return self.title

apps/doc/views.py
import logging
import requests

from django.shortcuts import render
from django.utils.encoding import escape_uri_path
from django.views import View
from django.conf import settings
from django.http import FileResponse, Http404

from .models import Doc

logger = logging.getLogger('django')

def doc_index(request):
    '''
    route: /
    :param request:
    :return: render
    '''
    docs = Doc.objects.defer('author', 'create_time', 'update_time', 'is_delete').filter(is_delete=False)
    return render(request, 'doc/docDownload.html', locals())


class DocDownload(View):
    '''
    doc download view
    route:
    '''
    def get(self, request, doc_id):
        doc = Doc.objects.only('file_url').filter(is_delete=False, id=doc_id).first()
        if doc:
            doc_url = doc.file_url
            doc_url = settings.SITE_DOMAIN_PORT + doc_url if not doc_url.startswith('http') else doc_url
            doc_name = doc.title
            try:
                # res = FileResponse(open(doc_url, 'rb'))
                res = FileResponse(requests.get(doc_url, stream=True))
            except Exception as e:
                logger.info("获取文档内容出现异常：\n{}".format(e))
                raise Http404("文档下载异常！")

            ex_name = doc_url.split('.')[-1]
            # https://stackoverflow.com/questions/23714383/what-are-all-the-possible-values-for-http-content-type-header
            # http://www.iana.org/assignments/media-types/media-types.xhtml#image
            if not ex_name:
                raise Http404('<h1>文档url异常</h1>')
            else:
                ex_name = ex_name.lower()

            if ex_name == "pdf":
                res["Content-type"] = "application/pdf"
            elif ex_name == "zip":
                res["Content-type"] = "application/zip"
            elif ex_name == "doc":
                res["Content-type"] = "application/msword"
            elif ex_name == "xls":
                res["Content-type"] = "application/vnd.ms-excel"
            elif ex_name == "docx":
                res["Content-type"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            elif ex_name == "ppt":
                res["Content-type"] = "application/vnd.ms-powerpoint"
            elif ex_name == "pptx":
                res["Content-type"] = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
            else:
                raise Http404("文档格式不正确！")

            final_filename = doc_name + '.' + ex_name
            # doc_filename = escape_uri_path(doc_url.split('/')[-1])
            doc_filename = escape_uri_path(final_filename)
            # 设置为inline，会直接打开,设置attachment，浏览器不会在下载完成后直接打开
            res["Content-Disposition"] = "attachment; filename*=UTF-8''{}".format(doc_filename)
            return res

        else:
            raise Http404('<h1>文档不存在</h1>')

templates/doc/docDownload.html
{% extends 'base/base.html' %}

{% block title %}
  文档下载
{% endblock %}

{% block link %}
  <link rel="stylesheet" href={% static 'css/doc/docDownload.css' %}>
{% endblock %}

{% block main_contain %}
  <div class="main-contain ">
    <div class="banner">
      <img src="/media/doc_banner_2.jpg" alt="">
    </div>
    <div class="pay-doc-contain">
      <ul class="pay-list">

        {% for doc in docs %}
          <li class="pay-item">
{#          <div class="pay-img doc"></div>#}
            <img src="{{ doc.image_url }}" alt="" class="pay-img doc">
          <div class="d-contain">
            <p class="doc-title">{{ doc.title }}</p>
            <p class="doc-desc">{{ doc.desc }}</p>

            <!-- /www/?xxx -->
            <a href="{% url 'doc:doc_download' doc.id %}" class="pay-price">下载</a>
          </div>
        </li>
        {% endfor %}


{#        <li class="pay-item">#}
{#          <div class="pay-img doc"></div>#}
{#          <div class="d-contain">#}
{#            <p class="doc-title">python cookbook 3.0 教程</p>#}
{#            <p class="doc-desc">强烈推荐的python 教程。</p>#}
{##}
{#            <!-- /www/?xxx -->#}
{#            <a href="#" class="pay-price">下载</a>#}
{#          </div>#}
{#        </li>#}
{##}
{#        <li class="pay-item">#}
{#          <div class="pay-img doc"></div>#}
{#          <div class="pay-contain">#}
{#            <p class="pay-title">流畅的Python</p>#}
{#            <p class="pay-desc">【本书特色】#}
{##}
{#              本书由奋战在Python开发一线近20年的Luciano Ramalho执笔，Victor Stinner、Alex#}
{#              Martelli等Python大咖担纲技术审稿人，从语言设计层面剖析编程细节，兼顾Python 3和Python#}
{#              2，告诉你Python中不亲自动手实践就无法理解的语言陷阱成因和解决之道，教你写出风格地道的Python代码。</p>#}
{##}
{#            <!-- /www/?xxx -->#}
{#            <a href="#" class="pay-price">下载</a>#}
{#          </div>#}
{#        </li>#}
{##}
{#        <li class="pay-item">#}
{#          <div class="pay-img doc"></div>#}
{#          <div class="pay-contain">#}
{#            <p class="pay-title">深入Flask</p>#}
{#            <p class="pay-desc">深入Flask，强烈推荐！</p>#}
{##}
{#            <!-- /www/?xxx -->#}
{#            <a href="#" class="pay-price">下载</a>#}
{#          </div>#}
{#        </li>#}

      </ul>
    </div>
  </div>
{% endblock %}

{% block side %}
  <!-- side start -->
  <aside class="side">
    <div class="side-activities">
      <h3 class="activities-title">在线课堂<a href="javascript:void(0)">更多</a></h3>
      <div class="activities-img">
        <a href="javascript:void(0);" target="_blank">
          <img src={% static 'images/english.jpg' %} alt="title">
        </a>
        <p class="activities-tips">对话国外小姐姐</p>
      </div>
      <ul class="activities-list">
        <li>
          <a href="javascript:void(0);" target="_blank">
            <span class="active-status active-start">报名中</span>
            <span class="active-title"><a
               href="https://www.shiguangkey.com/course/2432"> Django 项目班</a></span>
          </a>
        </li>
        <li>
          <a href="javascript:void(0);" target="_blank">
            <span class="active-status active-end">已结束</span>
            <span class="active-title"><a
               href="https://www.shiguangkey.com/course/2321">Python入门基础班</a></span>
          </a>
        </li>
      </ul>
    </div>
    <div class="side-attention clearfix">
      <h3 class="attention-title">关注我</h3>
      <ul class="side-attention-address">
        <li>
          <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-GitHub"></i>pywjh</a>
        </li>
        <li>
          <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-zhihu"
                                                           style="color:rgb(0, 108, 226);"></i>pywjh</a>
        </li>
        <li>
          <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-weibo"
                                                           style="color:rgb(245,92,110);"></i>pywjh</a>
        </li>
      </ul>
      <div class="side-attention-qr">
        <p>扫码关注</p>
      </div>
    </div>
{% endblock %}